/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/settings/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get public settings */
        get: operations["getPublicSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/2fa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete 2FA login */
        post: operations["login2fa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/send-verify-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send email verification code */
        post: operations["sendVerifyCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/validate-promo-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate promo code */
        post: operations["validatePromoCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/validate-invitation-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate invitation code */
        post: operations["validateInvitationCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request password reset */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset password with token */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user with run_mode */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/revoke-all-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke all sessions */
        post: operations["revokeAllSessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user profile */
        get: operations["getUserProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update user profile */
        put: operations["updateUserProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change password */
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/totp/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get TOTP status */
        get: operations["getTotpStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/totp/verification-method": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get verification method for TOTP setup/disable */
        get: operations["getTotpVerificationMethod"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/totp/send-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send email verification code for TOTP operations */
        post: operations["sendTotpCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/totp/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Setup TOTP (get QR code) */
        post: operations["setupTotp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/totp/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable TOTP with verification code */
        post: operations["enableTotp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/totp/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable TOTP */
        post: operations["disableTotp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API keys (paginated) */
        get: operations["listKeys"];
        put?: never;
        /** Create API key */
        post: operations["createKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API key by ID */
        get: operations["getKey"];
        /** Update API key */
        put: operations["updateKey"];
        post?: never;
        /** Delete API key */
        delete: operations["deleteKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available groups for current user */
        get: operations["getAvailableGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get group rate multipliers */
        get: operations["getGroupRates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List usage logs (paginated) */
        get: operations["listUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usage/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get usage log by ID */
        get: operations["getUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usage/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get usage statistics */
        get: operations["getUsageStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usage/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard statistics */
        get: operations["getDashboardStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usage/dashboard/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get usage trend data */
        get: operations["getDashboardTrend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usage/dashboard/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get model usage breakdown */
        get: operations["getDashboardModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usage/dashboard/api-keys-usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch get API key usage stats */
        post: operations["batchApiKeysUsage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user announcements */
        get: operations["listAnnouncements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/announcements/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark announcement as read */
        post: operations["markAnnouncementRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redeem a code */
        post: operations["redeemCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/redeem/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get redeem history */
        get: operations["getRedeemHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all subscriptions */
        get: operations["listSubscriptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active subscriptions */
        get: operations["listActiveSubscriptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get subscription progress with usage windows */
        get: operations["getSubscriptionProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get subscription summary */
        get: operations["getSubscriptionSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponse: {
            /** @description 0 = success, otherwise HTTP status code */
            code: number;
            message: string;
            reason?: string;
            metadata?: {
                [key: string]: string;
            };
            data?: unknown;
        };
        PaginatedData: {
            items: unknown[];
            /** Format: int64 */
            total: number;
            page: number;
            page_size: number;
            pages: number;
        };
        User: {
            /** Format: int64 */
            id: number;
            /** Format: email */
            email: string;
            username: string;
            role: string;
            /** Format: double */
            balance: number;
            concurrency: number;
            status: string;
            allowed_groups?: number[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            api_keys?: components["schemas"]["APIKey"][];
            subscriptions?: components["schemas"]["UserSubscription"][];
        };
        APIKey: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            user_id: number;
            key: string;
            name: string;
            /** Format: int64 */
            group_id?: number | null;
            /** @enum {string} */
            status: "active" | "inactive";
            ip_whitelist?: string[];
            ip_blacklist?: string[];
            /** Format: date-time */
            last_used_at?: string | null;
            /**
             * Format: double
             * @description USD, 0 = unlimited
             */
            quota: number;
            /** Format: double */
            quota_used: number;
            /** Format: date-time */
            expires_at?: string | null;
            /** Format: double */
            rate_limit_5h?: number;
            /** Format: double */
            rate_limit_1d?: number;
            /** Format: double */
            rate_limit_7d?: number;
            /** Format: double */
            usage_5h?: number;
            /** Format: double */
            usage_1d?: number;
            /** Format: double */
            usage_7d?: number;
            /** Format: date-time */
            window_5h_start?: string | null;
            /** Format: date-time */
            window_1d_start?: string | null;
            /** Format: date-time */
            window_7d_start?: string | null;
            /** Format: date-time */
            reset_5h_at?: string | null;
            /** Format: date-time */
            reset_1d_at?: string | null;
            /** Format: date-time */
            reset_7d_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            user?: components["schemas"]["User"];
            group?: components["schemas"]["Group"];
        };
        Group: {
            /** Format: int64 */
            id: number;
            name: string;
            description: string;
            platform: string;
            /** Format: double */
            rate_multiplier: number;
            is_exclusive: boolean;
            status: string;
            subscription_type: string;
            /** Format: double */
            daily_limit_usd?: number | null;
            /** Format: double */
            weekly_limit_usd?: number | null;
            /** Format: double */
            monthly_limit_usd?: number | null;
            /** Format: double */
            image_price_1k?: number | null;
            /** Format: double */
            image_price_2k?: number | null;
            /** Format: double */
            image_price_4k?: number | null;
            claude_code_only?: boolean;
            /** Format: int64 */
            fallback_group_id?: number | null;
            /** Format: int64 */
            fallback_group_id_on_invalid_request?: number | null;
            allow_messages_dispatch?: boolean;
            require_oauth_only?: boolean;
            require_privacy_set?: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        UsageLog: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            user_id: number;
            /** Format: int64 */
            api_key_id: number;
            /** Format: int64 */
            account_id: number;
            request_id: string;
            model: string;
            service_tier?: string | null;
            reasoning_effort?: string | null;
            inbound_endpoint?: string | null;
            upstream_endpoint?: string | null;
            /** Format: int64 */
            group_id?: number | null;
            /** Format: int64 */
            subscription_id?: number | null;
            input_tokens: number;
            output_tokens: number;
            cache_creation_tokens?: number;
            cache_read_tokens?: number;
            cache_creation_5m_tokens?: number;
            cache_creation_1h_tokens?: number;
            /** Format: double */
            input_cost?: number;
            /** Format: double */
            output_cost?: number;
            /** Format: double */
            cache_creation_cost?: number;
            /** Format: double */
            cache_read_cost?: number;
            /** Format: double */
            total_cost: number;
            /** Format: double */
            actual_cost: number;
            /** Format: double */
            rate_multiplier: number;
            billing_type: number;
            request_type: string;
            stream: boolean;
            openai_ws_mode?: boolean;
            duration_ms?: number | null;
            first_token_ms?: number | null;
            image_count?: number;
            image_size?: string | null;
            media_type?: string | null;
            user_agent?: string | null;
            cache_ttl_overridden?: boolean;
            billing_mode?: string | null;
            /** Format: date-time */
            created_at: string;
            user?: components["schemas"]["User"];
            api_key?: components["schemas"]["APIKey"];
            group?: components["schemas"]["Group"];
            subscription?: components["schemas"]["UserSubscription"];
        };
        UserSubscription: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            user_id: number;
            /** Format: int64 */
            group_id: number;
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            expires_at: string;
            status: string;
            /** Format: date-time */
            daily_window_start?: string | null;
            /** Format: date-time */
            weekly_window_start?: string | null;
            /** Format: date-time */
            monthly_window_start?: string | null;
            /** Format: double */
            daily_usage_usd: number;
            /** Format: double */
            weekly_usage_usd: number;
            /** Format: double */
            monthly_usage_usd: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            user?: components["schemas"]["User"];
            group?: components["schemas"]["Group"];
        };
        UserAnnouncement: {
            /** Format: int64 */
            id: number;
            title: string;
            content: string;
            notify_mode: string;
            /** Format: date-time */
            starts_at?: string | null;
            /** Format: date-time */
            ends_at?: string | null;
            /** Format: date-time */
            read_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        RedeemCode: {
            /** Format: int64 */
            id: number;
            code: string;
            type: string;
            /** Format: double */
            value: number;
            status: string;
            /** Format: int64 */
            used_by?: number | null;
            /** Format: date-time */
            used_at?: string | null;
            /** Format: int64 */
            group_id?: number | null;
            validity_days: number;
            notes?: string | null;
            /** Format: date-time */
            created_at: string;
            user?: components["schemas"]["User"];
            group?: components["schemas"]["Group"];
        };
        PublicSettings: {
            registration_enabled: boolean;
            email_verify_enabled: boolean;
            registration_email_suffix_whitelist?: string[];
            promo_code_enabled?: boolean;
            password_reset_enabled?: boolean;
            invitation_code_enabled?: boolean;
            totp_enabled: boolean;
            turnstile_enabled: boolean;
            turnstile_site_key?: string;
            site_name: string;
            site_logo?: string;
            site_subtitle?: string;
            api_base_url?: string;
            contact_info?: string;
            doc_url?: string;
            home_content?: string;
            hide_ccs_import_button?: boolean;
            purchase_subscription_enabled?: boolean;
            purchase_subscription_url?: string;
            custom_menu_items?: components["schemas"]["CustomMenuItem"][];
            custom_endpoints?: components["schemas"]["CustomEndpoint"][];
            linuxdo_oauth_enabled?: boolean;
            backend_mode_enabled?: boolean;
            version: string;
        };
        CustomMenuItem: {
            id: string;
            label: string;
            icon_svg?: string;
            url: string;
            visibility: string;
            sort_order: number;
        };
        CustomEndpoint: {
            name: string;
            endpoint: string;
            description?: string;
        };
        AuthResponse: {
            access_token: string;
            refresh_token?: string;
            expires_in?: number;
            token_type: string;
            user: components["schemas"]["User"];
        };
        TotpLoginResponse: {
            requires_2fa: boolean;
            temp_token?: string;
            user_email_masked?: string;
        };
        RefreshTokenResponse: {
            access_token: string;
            refresh_token: string;
            expires_in: number;
            token_type: string;
        };
        SendVerifyCodeResponse: {
            message: string;
            countdown: number;
        };
        ValidatePromoCodeResponse: {
            valid: boolean;
            /** Format: double */
            bonus_amount?: number;
            error_code?: string;
            message?: string;
        };
        ValidateInvitationCodeResponse: {
            valid: boolean;
            error_code?: string;
        };
        UserWithRunMode: components["schemas"]["User"] & {
            run_mode: string;
        };
        TotpStatusResponse: {
            enabled: boolean;
            /** Format: int64 */
            enabled_at?: number | null;
            feature_enabled: boolean;
        };
        TotpSetupResponse: {
            secret: string;
            qr_code_url: string;
            setup_token: string;
            countdown: number;
        };
        UsageStats: {
            /** Format: int64 */
            total_requests: number;
            /** Format: int64 */
            total_input_tokens: number;
            /** Format: int64 */
            total_output_tokens: number;
            /** Format: int64 */
            total_cache_tokens: number;
            /** Format: int64 */
            total_tokens: number;
            /** Format: double */
            total_cost: number;
            /** Format: double */
            total_actual_cost: number;
            /** Format: double */
            average_duration_ms: number;
        };
        UserDashboardStats: {
            /** Format: int64 */
            total_api_keys: number;
            /** Format: int64 */
            active_api_keys: number;
            /** Format: int64 */
            total_requests: number;
            /** Format: int64 */
            total_input_tokens?: number;
            /** Format: int64 */
            total_output_tokens?: number;
            /** Format: int64 */
            total_cache_creation_tokens?: number;
            /** Format: int64 */
            total_cache_read_tokens?: number;
            /** Format: int64 */
            total_tokens: number;
            /** Format: double */
            total_cost: number;
            /** Format: double */
            total_actual_cost: number;
            /** Format: int64 */
            today_requests: number;
            /** Format: int64 */
            today_input_tokens?: number;
            /** Format: int64 */
            today_output_tokens?: number;
            /** Format: int64 */
            today_cache_creation_tokens?: number;
            /** Format: int64 */
            today_cache_read_tokens?: number;
            /** Format: int64 */
            today_tokens: number;
            /** Format: double */
            today_cost: number;
            /** Format: double */
            today_actual_cost: number;
            /** Format: double */
            average_duration_ms?: number;
            /** Format: int64 */
            rpm?: number;
            /** Format: int64 */
            tpm?: number;
        };
        TrendDataPoint: {
            date: string;
            /** Format: int64 */
            requests: number;
            /** Format: int64 */
            input_tokens: number;
            /** Format: int64 */
            output_tokens: number;
            /** Format: int64 */
            cache_creation_tokens?: number;
            /** Format: int64 */
            cache_read_tokens?: number;
            /** Format: int64 */
            total_tokens: number;
            /** Format: double */
            cost: number;
            /** Format: double */
            actual_cost: number;
        };
        ModelStat: {
            model: string;
            /** Format: int64 */
            requests: number;
            /** Format: int64 */
            input_tokens: number;
            /** Format: int64 */
            output_tokens: number;
            /** Format: int64 */
            cache_creation_tokens?: number;
            /** Format: int64 */
            cache_read_tokens?: number;
            /** Format: int64 */
            total_tokens: number;
            /** Format: double */
            cost: number;
            /** Format: double */
            actual_cost: number;
        };
        BatchAPIKeyUsageStats: {
            /** Format: int64 */
            api_key_id: number;
            /** Format: double */
            today_actual_cost: number;
            /** Format: double */
            total_actual_cost: number;
        };
        UsageWindowProgress: {
            /** Format: double */
            limit_usd: number;
            /** Format: double */
            used_usd: number;
            /** Format: double */
            remaining_usd: number;
            /** Format: double */
            percentage: number;
            /** Format: date-time */
            window_start: string;
            /** Format: date-time */
            resets_at: string;
            /** Format: int64 */
            resets_in_seconds: number;
        };
        SubscriptionProgress: {
            /** Format: int64 */
            id: number;
            group_name: string;
            /** Format: date-time */
            expires_at: string;
            expires_in_days: number;
            daily?: components["schemas"]["UsageWindowProgress"];
            weekly?: components["schemas"]["UsageWindowProgress"];
            monthly?: components["schemas"]["UsageWindowProgress"];
        };
        SubscriptionProgressInfo: {
            subscription?: components["schemas"]["UserSubscription"];
            progress?: components["schemas"]["SubscriptionProgress"];
        };
        SubscriptionSummaryItem: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            group_id: number;
            group_name: string;
            status: string;
            /** Format: double */
            daily_used_usd?: number;
            /** Format: double */
            daily_limit_usd?: number;
            /** Format: double */
            weekly_used_usd?: number;
            /** Format: double */
            weekly_limit_usd?: number;
            /** Format: double */
            monthly_used_usd?: number;
            /** Format: double */
            monthly_limit_usd?: number;
            expires_at?: string | null;
        };
        SubscriptionSummary: {
            active_count: number;
            /** Format: double */
            total_used_usd: number;
            subscriptions: components["schemas"]["SubscriptionSummaryItem"][];
        };
        MessageResponse: {
            message: string;
        };
        SuccessResponse: {
            success: boolean;
        };
        DashboardTrendResponse: {
            trend: components["schemas"]["TrendDataPoint"][];
            start_date: string;
            end_date: string;
            granularity: string;
        };
        DashboardModelsResponse: {
            models: components["schemas"]["ModelStat"][];
            start_date: string;
            end_date: string;
        };
        VerificationMethod: {
            method: string;
        };
    };
    responses: never;
    parameters: {
        PageParam: number;
        PageSizeParam: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPublicSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["PublicSettings"];
                    };
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                    verify_code?: string;
                    turnstile_token?: string;
                    promo_code?: string;
                    invitation_code?: string;
                };
            };
        };
        responses: {
            /** @description Registration successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["AuthResponse"];
                    };
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                    turnstile_token?: string;
                };
            };
        };
        responses: {
            /** @description Login successful (or requires 2FA) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["AuthResponse"] | components["schemas"]["TotpLoginResponse"];
                    };
                };
            };
        };
    };
    login2fa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    temp_token: string;
                    totp_code: string;
                };
            };
        };
        responses: {
            /** @description 2FA login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["AuthResponse"];
                    };
                };
            };
        };
    };
    sendVerifyCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    turnstile_token?: string;
                };
            };
        };
        responses: {
            /** @description Code sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["SendVerifyCodeResponse"];
                    };
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refresh_token: string;
                };
            };
        };
        responses: {
            /** @description Token refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["RefreshTokenResponse"];
                    };
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    refresh_token?: string;
                };
            };
        };
        responses: {
            /** @description Logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["MessageResponse"];
                    };
                };
            };
        };
    };
    validatePromoCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                };
            };
        };
        responses: {
            /** @description Validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["ValidatePromoCodeResponse"];
                    };
                };
            };
        };
    };
    validateInvitationCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                };
            };
        };
        responses: {
            /** @description Validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["ValidateInvitationCodeResponse"];
                    };
                };
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    turnstile_token?: string;
                };
            };
        };
        responses: {
            /** @description Reset email sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["MessageResponse"];
                    };
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    token: string;
                    new_password: string;
                };
            };
        };
        responses: {
            /** @description Password reset successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["MessageResponse"];
                    };
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["UserWithRunMode"];
                    };
                };
            };
        };
    };
    revokeAllSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["MessageResponse"];
                    };
                };
            };
        };
    };
    getUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["User"];
                    };
                };
            };
        };
    };
    updateUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username?: string;
                };
            };
        };
        responses: {
            /** @description Updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["User"];
                    };
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    old_password: string;
                    new_password: string;
                };
            };
        };
        responses: {
            /** @description Password changed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["MessageResponse"];
                    };
                };
            };
        };
    };
    getTotpStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TOTP status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["TotpStatusResponse"];
                    };
                };
            };
        };
    };
    getTotpVerificationMethod: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification method */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["VerificationMethod"];
                    };
                };
            };
        };
    };
    sendTotpCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Code sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["SuccessResponse"];
                    };
                };
            };
        };
    };
    setupTotp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    email_code?: string;
                    password?: string;
                };
            };
        };
        responses: {
            /** @description TOTP setup info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["TotpSetupResponse"];
                    };
                };
            };
        };
    };
    enableTotp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    totp_code: string;
                    setup_token: string;
                };
            };
        };
        responses: {
            /** @description TOTP enabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["SuccessResponse"];
                    };
                };
            };
        };
    };
    disableTotp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    email_code?: string;
                    password?: string;
                };
            };
        };
        responses: {
            /** @description TOTP disabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["SuccessResponse"];
                    };
                };
            };
        };
    };
    listKeys: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                page_size?: components["parameters"]["PageSizeParam"];
                search?: string;
                status?: "active" | "inactive";
                group_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated API keys */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["PaginatedData"] & {
                            items?: components["schemas"]["APIKey"][];
                        };
                    };
                };
            };
        };
    };
    createKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** Format: int64 */
                    group_id?: number | null;
                    custom_key?: string | null;
                    ip_whitelist?: string[];
                    ip_blacklist?: string[];
                    /** Format: double */
                    quota?: number | null;
                    expires_in_days?: number | null;
                    /** Format: double */
                    rate_limit_5h?: number | null;
                    /** Format: double */
                    rate_limit_1d?: number | null;
                    /** Format: double */
                    rate_limit_7d?: number | null;
                };
            };
        };
        responses: {
            /** @description API key created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["APIKey"];
                    };
                };
            };
        };
    };
    getKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["APIKey"];
                    };
                };
            };
        };
    };
    updateKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    /** Format: int64 */
                    group_id?: number | null;
                    /** @enum {string} */
                    status?: "active" | "inactive";
                    ip_whitelist?: string[];
                    ip_blacklist?: string[];
                    /** Format: double */
                    quota?: number | null;
                    /** @description ISO 8601 or empty string to clear */
                    expires_at?: string | null;
                    reset_quota?: boolean;
                    /** Format: double */
                    rate_limit_5h?: number | null;
                    /** Format: double */
                    rate_limit_1d?: number | null;
                    /** Format: double */
                    rate_limit_7d?: number | null;
                    reset_rate_limit_usage?: boolean;
                };
            };
        };
        responses: {
            /** @description Updated API key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["APIKey"];
                    };
                };
            };
        };
    };
    deleteKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["MessageResponse"];
                    };
                };
            };
        };
    };
    getAvailableGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available groups */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["Group"][];
                    };
                };
            };
        };
    };
    getGroupRates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group rates map */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: {
                            [key: string]: number;
                        };
                    };
                };
            };
        };
    };
    listUsage: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                page_size?: components["parameters"]["PageSizeParam"];
                api_key_id?: number;
                model?: string;
                request_type?: string;
                stream?: boolean;
                billing_type?: number;
                start_date?: string;
                end_date?: string;
                timezone?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated usage logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["PaginatedData"] & {
                            items?: components["schemas"]["UsageLog"][];
                        };
                    };
                };
            };
        };
    };
    getUsage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usage log */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["UsageLog"];
                    };
                };
            };
        };
    };
    getUsageStats: {
        parameters: {
            query?: {
                api_key_id?: number;
                period?: "today" | "week" | "month";
                start_date?: string;
                end_date?: string;
                timezone?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usage statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["UsageStats"];
                    };
                };
            };
        };
    };
    getDashboardStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["UserDashboardStats"];
                    };
                };
            };
        };
    };
    getDashboardTrend: {
        parameters: {
            query?: {
                start_date?: string;
                end_date?: string;
                granularity?: string;
                timezone?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trend data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["DashboardTrendResponse"];
                    };
                };
            };
        };
    };
    getDashboardModels: {
        parameters: {
            query?: {
                start_date?: string;
                end_date?: string;
                timezone?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Model stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["DashboardModelsResponse"];
                    };
                };
            };
        };
    };
    batchApiKeysUsage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    api_key_ids: number[];
                };
            };
        };
        responses: {
            /** @description Batch usage stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: {
                            stats?: {
                                [key: string]: components["schemas"]["BatchAPIKeyUsageStats"];
                            };
                        };
                    };
                };
            };
        };
    };
    listAnnouncements: {
        parameters: {
            query?: {
                unread_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Announcements list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["UserAnnouncement"][];
                    };
                };
            };
        };
    };
    markAnnouncementRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Marked as read */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["MessageResponse"];
                    };
                };
            };
        };
    };
    redeemCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                };
            };
        };
        responses: {
            /** @description Redeem result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["RedeemCode"];
                    };
                };
            };
        };
    };
    getRedeemHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redeem history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["RedeemCode"][];
                    };
                };
            };
        };
    };
    listSubscriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscriptions list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["UserSubscription"][];
                    };
                };
            };
        };
    };
    listActiveSubscriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active subscriptions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["UserSubscription"][];
                    };
                };
            };
        };
    };
    getSubscriptionProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription progress */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["SubscriptionProgressInfo"][];
                    };
                };
            };
        };
    };
    getSubscriptionSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["SubscriptionSummary"];
                    };
                };
            };
        };
    };
}
